### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by RiRa12621**
update son and rest-client to a more recent version

### CODE REVIEW

**Comment by burnettk** [comment]
You need to run `bundle` locally and commit the resulting Gemfile.lock.

**Comment by bitflingr** [comment]
I copied changes and updated a few other gems.  Thanks for the heads up!  Ill also look into a few other security updates that i am seeing in gemnasium currently.

**Comment by bitflingr** [comment]
0.8.2 was released on rubygems.

**Comment by RiRa12621** [comment]
very much appreciated

**Pull request closed without merging**
